apiVersion: v1
kind: Service
metadata:
  name: panstackdriver 
  namespace: istio-system
  labels:
    app: panstackdriver 
spec:
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 8889
    targetPort: 8889
  selector:
    app: panstackdriver 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: panstackdriver 
  namespace: istio-system
  labels:
    app: panstackdriver 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: panstackdriver 
      annotations:
        sidecar.istio.io/inject: "false"
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      containers:
      - name: panstackdriver 
        image: vinayvenkat/panstackdriver:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8889
        volumeMounts:
        - name: transient-storage
          mountPath: /volume
      volumes:
      - name: transient-storage
        emptyDir: {}
